language: python
sudo: false
python:
 - '2.7'
 - '3.3'
cache:
  directories:
    - ~/virtualenv
install:
 - wget public-travis-scripts.polysquare.org/python-install.sh
 - wget public-travis-scripts.polysquare.org/python-lint.sh
 - wget public-travis-scripts.polysquare.org/project-lint.sh
 - wget public-travis-scripts.polysquare.org/python-coverage.sh
 - wget public-travis-scripts.polysquare.org/python-tests.sh
 - bash python-install.sh
script:
 - bash python-lint.sh -m psqtraviscontainer
 - bash project-lint.sh -d . -e py 
 - bash python-tests.sh -m psqtraviscontainer
after_success:
 - bash python-coverage.sh
