language: python
sudo: false
cache:
  directories:
  - ~/virtualenv
python:
- '2.7'
- '3.3'
install:
- curl -LSs public-travis-scripts.polysquare.org/python-setup-with-doc.sh | bash
script:
- export MODULE=psqtraviscontainer
- curl -LSs public-travis-scripts.polysquare.org/python-test-module.sh | bash
after_success:
- curl -LSs public-travis-scripts.polysquare.org/python-coverage.sh | bash
